### ISSUE TITLE
Request to add tintin++ from pkgsrc-wip

### ISSUE THREAD

**Issue by kflu** [NetBSD/pkgsrc#110]
I added a package tintin++ in pkgsrc-wip. Can you help upstream it to pkgsrc? The pkgsrc-wip commit is [5b961c0c13ec41cd933d0574d6386420ca5e5370](https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=commit;h=5b961c0c13ec41cd933d0574d6386420ca5e5370). 

I tested it on macos:

```
bmake package
sudo bmake install
```

**Comment by iamleot** [comment]
@kflu Hello!

Possible minor suggestions:

* please always run `pkglint -Wall` and review and fix possible warnings: in that case `GITHUB_PROJECT` should be sorted... but... actually... `GITHUB_PROJECT` can be completely omitted because it is derived from `PKGBASE` that should be already `tintin` (so, please remove completely `GITHUB_PROJECT` not needed redefinition)
* Instead of hardcoding `GITHUB_RELEASE` with the version number please change it to `GITHUB_RELEASE= ${PKGVERSION_NOREV}`. In this way when updating just the version number in `DISTNAME` needs to be bumped.
* `HAS_CONFIGURE` is not needed because there is already `GNU_CONFIGURE`

Thank you!

**Comment by kflu** [comment]
Sorry, my version of the pkglint (from joyent pkgsrc for macos) says everything looks fine:

```
pkglint -V
21.4.0

pkglint  -Wall
Looks fine.
```

I tried to build pkglint, but there's an error about building go.

**Comment by kflu** [comment]
OK just fixed all the problems as suggested. Please see pkgsrc-wip f4ee8f05ca07be36d7ad34ccc733f5366dd423fd
