### ISSUE TITLE
404 error on "pkgin update"

### ISSUE THREAD

**Issue by kimono-koans** [NetBSD/pkgsrc#73]
Terminal Output:

-(~:$)-> sudo pkgin update
Password:
processing remote summary (https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All)...
pkgin: Could not fetch https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/pkg_summary.gz

-(~:$)-> wget https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/pkg_summary.gz
--2020-07-13 16:21:41--  https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/pkg_summary.gz
Resolving pkgsrc.joyent.com (pkgsrc.joyent.com)... 165.225.148.58
Connecting to pkgsrc.joyent.com (pkgsrc.joyent.com)|165.225.148.58|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-13 16:21:41 ERROR 404: Not Found.

**Comment by jperkin** [comment]
Hi, the repository is currently deliberately unavailable in order to ensure users do not perform an update and cause problems on their systems.  As per <https://twitter.com/jperkin/status/1281253912717262850> you'll need to run `pkg_add mksh` now, and then in the next few days when I re-enable the repository the upgrade should proceed smoothly.

Sorry that it's currently unavailable, this is a rare event, but one that I want to ensure is minimised as much as possible.  I'll update this ticket when it's up and running again.

FWIW in future you may want to raise this issue over at our fork (e.g. <https://github.com/joyent/pkgsrc/issues/275>), as there's not much that other NetBSD developers can do about our repository, though this repository is suitable for general pkgsrc queries or patches.  Thanks.

**Comment by jperkin** [comment]
This repository is now back online, please see <https://mail-index.netbsd.org/pkgsrc-users/2020/07/16/msg031767.html> for further information.  Thanks, and apologies again for the downtime.
